# Generated by Django 2.0.6 on 2019-05-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_string',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, verbose_name='用户注册码')),
                ('code_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_confirm',
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('usercode', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('sellphone', models.IntegerField(blank=True, null=True)),
                ('listnote', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_class',
            },
        ),
        migrations.CreateModel(
            name='TGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=20, null=True)),
                ('artist', models.CharField(blank=True, max_length=10, null=True)),
                ('marketprice', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sales', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.BigIntegerField(blank=True, null=True)),
                ('markettime', models.DateField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=50, null=True)),
                ('classid', models.ForeignKey(blank=True, db_column='classid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TClass')),
            ],
            options={
                'db_table': 't_goods',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.FloatField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(blank=True, max_length=40, null=True)),
                ('receive_address', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TOrderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=40, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TGoods')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TOrder')),
            ],
            options={
                'db_table': 't_orderitem',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('salt', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=70, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('has_confirm', models.BooleanField(default=False, verbose_name='是否确认')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='torder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TUser'),
        ),
        migrations.AddField(
            model_name='taddress',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.TUser'),
        ),
        migrations.AddField(
            model_name='confirm_string',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TUser', verbose_name='关联的用户'),
        ),
    ]
